### ISSUE TITLE
Not available on Google WebStore

### ISSUE THREAD

**Issue by Blackwidow-sudo** [truedread/netflix-1080p#103]
The link in your readme is dead.
Cant find the extension for chrome anymore.

**Comment by ststeja** [comment]
download it and load it.

**Comment by Blackwidow-sudo** [comment]
> download it and load it.

What do you mean with download it and load it?
Do you mean downloading from here?

**Comment by d0ku** [comment]
Yes, you can download it from [releases page](https://github.com/truedread/netflix-1080p/releases).
* Download the source code e.g. zip archive
* Extract it to some directory
* Turn on developer mode in chrome extensions manager
* "Load unpacked" and select directory you unpacked to

**Comment by truedread** [comment]
Duplicate of #67
