### ISSUE TITLE
Netflix 503's with extension enabled

### ISSUE THREAD

**Issue by jacobtriffo** [truedread/netflix-1080p#105]
As of today, I think netflix may have changed something, because yesterday the extension was working as-advertised, but tonight whenever I try to reach netflix.com the site appears to be down.

When I disable the extension and wait a bit, or clear cache/cookies, the site works fine and content plays normally, albeit at 720p

Javascript console stays blank, no errors reported and the site does not appear to attempt to load.

This is in Vivaldi running on Manjaro Linux
Kernel: 5.4.44-1-MANJARO
Vivaldi | 3.1.1929.45 (Stable channel) (64-bit)

**Comment by truedread** [comment]
Closing as major changes have been made that have probably fixed this.
