### ISSUE TITLE
All Videos stuck 

### ISSUE THREAD

**Issue by Bullzz** [truedread/netflix-1080p#107]
Is this project dead ?

**Comment by jangxx** [comment]
It certainly looks that way, but me and other people have picked up the development for many different browsers:

- https://github.com/TheGoddessInari/netflix-1080p-firefox
- https://github.com/lkmvip/netflix-4K-DDplus
- https://github.com/jangxx/netflix-1080p

**Comment by truedread** [comment]
Closing as major changes have been made that have probably fixed this.
