### ISSUE TITLE
Packaging: make authorship, URL more visible

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [truedread/netflix-1080p#110]
I installed your extension (for which, thanks). Then I had trouble discovering where I got it from. I found a reference to 'truedread' in the README. Yet, I think that the README - and perhaps some other part of the packaged materials - should include a reference to this repository (especially since there are multiple repositories with similar leafnames). Thanks,

**Comment by truedread** [comment]
My name is in the included license and README, as well as a link to the repository (one of the issues is linked) is in the README.
