### ISSUE TITLE
4k on 2k monitor have problem

### ISSUE THREAD

**Issue by Loukky** [truedread/netflix-1080p#118]
first, thanks @truedread this good addons.
i have use it on Chrome and Edge...
and now i have a 2k monitor, when i use Edge,i found this....
default play on 2k

![QQ截图20210902171041](https://user-images.githubusercontent.com/12481807/131816944-c20486ed-e98f-47ef-bb5c-51052252238e.png)
mabey is this reason
![QQ截图20210902171208](https://user-images.githubusercontent.com/12481807/131817176-d30507fd-7dad-4209-b0bd-54701812f883.png)
over 2k Bit rate is not select default,when i select 4k bit rate Manual.it play 4k very good..
![QQ截图20210902171459](https://user-images.githubusercontent.com/12481807/131817538-0f8ad9a8-7363-4310-81a4-f8c75cfc4f1c.png)
![QQ截图20210902171449](https://user-images.githubusercontent.com/12481807/131817546-428925f9-0141-4f6a-9552-6668d2bcbb2e.png)
test netflix video link:https://www.netflix.com/title/81410784

**Comment by phanluchoaofficial20** [comment]
I think if you got 4k on 2k monitor I think is very good, too advantageous.
