### ISSUE TITLE
Extension isn't working

### ISSUE THREAD

**Issue by SKDemon820** [truedread/netflix-1080p#121]
![Screen Shot 2021-11-22 at 12 20 18 PM](https://user-images.githubusercontent.com/62918850/142906952-017fa0e4-c81f-4492-badd-9b76e206e9bd.png)
It was working fine before but suddenly it isn't, I already tried reinstalling it and messing with the settings

**Comment by truedread** [comment]
Can you press Ctrl+Alt+Shift+S and verify that you're getting the highest quality stream?

**Comment by SKDemon820** [comment]
Idk what any of the specific info shown there means, but I can confirm that the extension is working again for me (It's coming through as 1080p).  Idk what caused the issue or what fixed it since I didn't change anything myself, but it's fine now.

**Comment by truedread** [comment]
I pushed an update a few days ago, which might've fixed things.
