### ISSUE TITLE
[Feature Request] Add support for Amazon Prime video

### ISSUE THREAD

**Issue by foundObjects** [truedread/netflix-1080p#122]
Any chance you could extend use of the DRM plugin to Amazon Prime URLs as well? I get terrible quality 720p video from Prime on Linux, much better quality on Windows and Android.

Cheers!

**Comment by truedread** [comment]
Not really possible, unfortunately. Amazon Prime only serves 1080p to Windows and Android because of DRM; Linux does not support VMP (verified media path, a feature of Widevine DRM that allows license servers to check if the CDM has been tampered with).

**Comment by ThreeDeeJay** [comment]
@truedread What about 5.1 surround?
Last I checked it worked with the Netflix addon, but Prime Video app doesn't even support surround so I've had to [use a Kodi addon with synced playback in the background to get 5.1](https://old.reddit.com/r/amazonprime/comments/90yz5c/how_to_get_51_surround_sound_on_amazon_prime/k3yaclx/)
