### ISSUE TITLE
Add-on makes player stuck on loading red circle while sound keeps playing

### ISSUE THREAD

**Issue by soufianefariss** [truedread/netflix-1080p#13]
Netflix runs fine when add-on is disabled.

**Comment by deewfrank** [comment]
this happens to me on the firefox extension, but on Chrome is working well.

**Comment by truedread** [comment]
Are you on version 1.3? This was fixed.

**Comment by soufianefariss** [comment]
I updated it. It works fine now!
Thanks for this.
