### ISSUE TITLE
Netflix updated playercore again, so it doesn't work

### ISSUE THREAD

**Issue by Cysioland** [truedread/netflix-1080p#14]
The Good Place doesn't load, Test Patterns show bitrates below 1000, only [this](https://www.netflix.com/watch/70138483?trackId=14277281) shows good results. Version of playercore loaded by the player differs from the one loaded by the extension.

**Comment by truedread** [comment]
Figured out what's going on: Netflix is now using VP9 on Chrome. I'm working right now to see how to force it back to H.264.

**Comment by Cysioland** [comment]
Chrome tells me it's got VP9 available. Can't we just make it work with that?

**Comment by truedread** [comment]
VP9 is going to look a lot worse than H.264 will. It's smaller, but that doesn't come without quality drawbacks. I just figured out how to force H.264, so I was going to push that. 1080p VP9 would have a bitrate of about ~2000kbps, while 1080p H.264 would have a bitrate of about ~5000kbps.

**Comment by Cysioland** [comment]
So, it's another way of them to skimp on bandwidth for subhumans^W non-Hollywood-approved platform users.

Fine, then. I mean, 5Mbps on 1080p looks stellar.

**Comment by truedread** [comment]
@Cysioland pushed the fix to master branch, Chrome store update incoming as well as beta branch update.

**Comment by Cysioland** [comment]
Works on test patterns, but not on certain Netflix Originals or Disney ones.

Moana: Playing bitrate (a/v): 96 / 2260 (853x480)
The Good Place S01E13: Playing bitrate (a/v): 96 / 830 (853x480)

On the other hand,

Aggretsuko S01E02: Playing bitrate (a/v): 96 / 5110 (1920x1080)

**Comment by Cysioland** [comment]
Thanks, it works, and I'm really glad you're maintaining this and you backported today's fix into beta. You're doing Dog's work.
