### ISSUE TITLE
playercore updated yet again

### ISSUE THREAD

**Issue by rdoursenaud** [truedread/netflix-1080p#16]
https://assets.nflxext.com/en_us/ffe/player/html/cadmium-playercore-6.0009.543.011.js

**Comment by truedread** [comment]
No point in updating the extension unless playback is affected. Netflix updates the player JS every week, and updating the extension along with it would produce a string of identical versions unless playback were affected in some way. If it has been, please make a separate issue detailing what has changed and why it warrants a new extension update.

**Comment by rdoursenaud** [comment]
Ok, didn't know that.
I thought it might be the reason why it wasn't working for me anymore.
Looks like it's an unrelated issue.
Anyway, thanks for your work!
