### ISSUE TITLE
 Why do not movies play in 1080p? And do the series play normally?

### ISSUE THREAD

**Issue by ricardopablo** [truedread/netflix-1080p#17]
I was doing some tests here and I realized that movies do not run above 480p and the series runs normally, why does this happen? And is there a solution to the case?

**Comment by truedread** [comment]
Read this thread: https://github.com/truedread/netflix-1080p/issues/2. It explains why some movies only play in SD. If you want them to play in 1080p you'll have to use the [beta branch](https://github.com/truedread/netflix-1080p/tree/beta).
