### ISSUE TITLE
[Feature Request] Firefox Support

### ISSUE THREAD

**Issue by Marc05** [truedread/netflix-1080p#18]
Any chance in providing a Firefox version of this extension? Currently, I am using the Windows 10 Store app, but I would much rather keep this within Firefox so I can make use of other extensions as well.

**Comment by truedread** [comment]
This is a Chrome extension; I have no plans to port this to Firefox. However, someone already has, but it's not updated. Check it out here: https://github.com/vladikoff/netflix-1080p-firefox. Might not work since it's not updated though.
