### ISSUE TITLE
How to help debug content that does not play 1080p

### ISSUE THREAD

**Issue by rvelhote** [truedread/netflix-1080p#24]
Hello truedread,

I've been testing this extension and found some movies that do not support 1080p. They keep playing at 480p with the extension on and 540p with the extension off. I can stream the content at 1080p using my PS4 so the content is available at that resolution.

Here are some examples:
- No Country for Old Men
- The Departed
- Lord of the Rings

How can I help debug these movies? I'm using Google Chrome 68.0.3440.106 in Ubuntu 16.04.

Thank you!

**Comment by truedread** [comment]
I'm getting 1080p for No Country for Old Men:
![](https://i.imgur.com/PgVBHGq.jpg)

What country are you streaming from? Can you include Chrome console logs?

**Comment by rvelhote** [comment]
Thank you for the reply!

I am in Portugal. Here is a screenshot of the console plus the player debug. Do you think it can be the the throughput? I mean, the player will only output 1080p with a high bitrate + throughput combo? I consistently get 2MBps (~24Mbps with my ADSL) which should be enough for FHD according to the docs.

![screenshot from 2018-08-18 10-28-44](https://user-images.githubusercontent.com/59101/44297936-b4346f80-a2d1-11e8-9b9e-99e11bfb4d1a.png)

**Comment by truedread** [comment]
Hmm, it’s getting the Edge manifest properly, so it should be playing 1080p. Can you take a screenshot of the bitrate dialog box (Ctrl+Alt+Shift+D) on the same video?

**Comment by rvelhote** [comment]
Sure. Here you go.

![screenshot from 2018-08-18 18-56-27](https://user-images.githubusercontent.com/59101/44301983-89213e80-a318-11e8-82cc-204ba0e2430a.png)

**Comment by truedread** [comment]
I'm more concerned about the fact that you aren't getting 1080p at all. I honestly have no idea why 1080p won't come in the manifest you're acquiring with the Edge ESN.

**Comment by rvelhote** [comment]
I managed to use a US VPN and got 1080p. The console reports `Manifest not locked to Edge, commencing normal playback`. This means for some reason it's regionally locked in Chrome but not on the PS4.

For The Departed and Lord of the Rings, however, the end result was the same. No 1080p. The console output is the same as I had in No Country for Old Men.

**Comment by jvschiavo** [comment]
Maybe you can ask Netflix support about why the movie doesn't play at 720p on web (as it should) but it plays at 1080p on PS4.

You don't need to mention anything you discussed in this GitHub page at all.

**Comment by rvelhote** [comment]
I thought about that however they mention that customer support [does not handle](https://help.netflix.com/en/node/23742) issues related to Linux and also they mention "up to 720p" so they make no promisses otherwise.

**Comment by Genius1237** [comment]
@rvelhote Could you guide me on where to look for the `videoTracks` variable that has the list of tracks returned by the manifest. I did some digging in the developer tools, setting breakpoints and so on, but was out of luck.

I'm on a linux and get only 540p for many TV shows  (non-netflix originals), while the same shows get 720p normally and 1080p with the extension on windows (Chrome and Firefox).

**Comment by truedread** [comment]
Closing as major changes have been made that have probably fixed this.
