### ISSUE TITLE
Are all AAC streams available in the same manifest simultaneously? 

### ISSUE THREAD

**Issue by stinkteeth** [truedread/netflix-1080p#25]
Is it not possible to have the 2.0 (64k/96k) aac streams available for selection when a 5.1 (192k) aac stream is available?

Of course, the extension can be disabled to regain the 2.0 aac streams, but then 1080p is lost.

There are some use cases where the 5.1 aac stream does not provide sufficient volume on a particular device (while the 2.0 aac streams always provides enough volume) but 1080p video is still desired.

**Comment by Kono14** [comment]
I would also love to have this option to have 1080p enabled but with 2.0 Audio, not 5.1.
Same reason as above, 5.1 channels on a 2-speaker system can be very weird sometimes.

**Comment by Kono14** [comment]
Just found out, that the "5.1 audio" feature was just added in the last update of this extension, in version 1.8. Also there was nothing else added in that update. 

So if you go back one version to 1.7 of this extension, you "**_loose_**" 5.1 audio and still get 1080p video. 😁
Uinstall extension from Chrome, download from here and drag manually to Chrome extension page: 
https://www.crx4chrome.com/crx/110671/

**Comment by truedread** [comment]
Fixed this in the latest commit. You can now select how many channels you want in the audio language selection menu of Netflix.
