### ISSUE TITLE
Make 5.1 audio optional

### ISSUE THREAD

**Issue by phaax** [truedread/netflix-1080p#27]
I don't have a 5.1 sound setup and with this extension I always get the 5.1 audio as default. It would be great if we could optionally disable the 5.1 audio altogether.

Simply commenting out the "heacc-5.1-dash" solves this perfectly, but an option would be very much appreciated.

```
var profiles = [
    "playready-h264mpl30-dash",
    "playready-h264mpl31-dash",
    "playready-h264mpl40-dash",
    "heaac-2-dash",
    //"heaac-5.1-dash",
    "simplesdh",
    "nflx-cmisc",
    "BIF240",
    "BIF320"
];
```

**Comment by phaax** [comment]
It reverts back to 5.1 after each episode unfortunately.

**Comment by truedread** [comment]
Added in latest release.
