### ISSUE TITLE
Activation of function showAllSubDubTracks.

### ISSUE THREAD

**Issue by fabrebatalla18** [truedread/netflix-1080p#3]
I am editing your extension to add the showAllSubDubTracks function and thus be able to show hidden languages, but I have the following problem, there are so many languages in some series that I can not fit on the screen, is there any way to fix it?

https://i.imgur.com/NfpVn4b.png

Mi edition is this:

>                             bGa: b(d, "showAllSubDubTracks", !0),

I changed 1 to 0 for active showAllSubDubTracks.

**Comment by truedread** [comment]
It would involve adding CSS properties to the two track list elements (track-list-audio and track-list-subtitles). I did this in Edge by modifying the WebUI JavaScript to add the "scrollable" class to both track lists:

```javascript
return u.createElement("div", {
    className: c("popup-content", "audio-subtitle-controller")
}, u.createElement(k, {
    className: c("track-list", "structural", "track-list-audio", "scrollable"),
    commandLoggingName: p.AUDIO
}, u.createElement(k, {
    className: c("track-list", "structural", "track-list-subtitles", "scrollable"),
    commandLoggingName: p.TIMED_TEXT
```

Then in the WebUI CSS I set the "scrollable" class to have the following properties:

```css
.scrollable {
    max-height: 300px;
    overflow-y: scroll;
}
```

I never tried it with Chrome; I only did this within Edge. Hope this helps.

**Comment by truedread** [comment]
I am closing this issue though, as I won't be enabling showAllSubDubTracks within my extension; my extension just enables 1080p within Chrome, nothing extra.

**Comment by fabrebatalla18** [comment]
Thanks, do you think you could implement it in your extension in a future version? And I apologize if I have not used the "issues" correctly, I am something new with github
