### ISSUE TITLE
Oops, Something Went Wrong, Unexpected Error

### ISSUE THREAD

**Issue by L0rdLogan** [truedread/netflix-1080p#34]
Hi.

I'm having an issue with Chrome V70 and Firefox V63 where having the plugin installed and enabled generates a "Oops something went wrong, unexpected error"

Only way to resolve this is to use netflix with the plugin disabled (not great as I record content off it using OBS for Archive purposes (the netflix original shows)

**Comment by furbino** [comment]
same here

**Comment by nhockey** [comment]
See my thread, the error has changed but the issue is the same. #30

**Comment by dereg666** [comment]
same happened to me on both chrome and firefox.

**Comment by truedread** [comment]
Duplicate of #30, closing
