### ISSUE TITLE
Some movies not working with latest 1.12

### ISSUE THREAD

**Issue by informatorius** [truedread/netflix-1080p#36]
https://www.netflix.com/watch/80058399
https://www.netflix.com/watch/80206300
https://www.netflix.com/watch/70213465
https://www.netflix.com/watch/80050060

All movies have resolution 853x480 and codec
Audio Track: mp4a.40.2
Video Track: video/mp4;codecs=avc1.640028 (avc)

**Comment by truedread** [comment]
Duplicate of #30
