### ISSUE TITLE
Selectable codec?

### ISSUE THREAD

**Issue by NovaPrima** [truedread/netflix-1080p#37]
I don't know how difficult this would be and thus how reasonable a request it is, but it seems like Netflix has been re-encoding things very recently and the video quality is quite often just plain bad. Since this extension tells Netflix that the user is on Android (right?), is it possible/would you consider telling it it's running a device that needs to fall back from what I assume is H.265 or AV1 to H.264 or VP9?

Perhaps I don't know what I'm talking about, but it'd potentially be a godsend to bypass these new bitstarved encodes.

**Comment by Aspectsec** [comment]
Read the #30 thread, they explain how it works (as well as the readme) and maybe you'll find an answer there too.

Cheers man.

**Comment by NovaPrima** [comment]
Just read through both, understood _some_. Evidently I should have said ChromeOS instead of Android.

**Comment by Aspectsec** [comment]
Any chromium browser yes. But right not every title is working with this extension due to some Netflix scripts changes. Truedread is working on it but need some time as he's still student, amazing work tho.

**Comment by Aspectsec** [comment]
Yeah I guess so if you look at the source code.

**Comment by truedread** [comment]
I'm not too sure if this is possible as with all the new changes Netflix is forcing Chrome to either sometimes get H.264 with 1080p, or just VP9 in SD (sometimes AVC-Hi in 720p). The extension *should* pick the best one automatically, and I can't see any reason for selecting a lower quality codec.

**Comment by NovaPrima** [comment]
I figured out a couple of weeks ago it's actually 'avchigh' that it's usually using, according to the stats page/display. My thinking was that forcing regular AVC (or another codec) would enable decent bitrates, but that might not be the cause after all, as The Haunting of Hill House is standard AVC yet episode 10 tops out at 1400kbps at 1080p. Thus my theory is most likely flawed.

**Comment by bryanbuckley** [comment]
@truedread , I was trying to use this extension as a "h264ify for netflix" since my computer can do (HW accel) avc but not (SW) VP9. Even with "use VP9 instead of h.264" unchecked, netflix uses vp9. Any idea if a feature like this would help my situation?
