### ISSUE TITLE
Audio and video not synchronized

### ISSUE THREAD

**Issue by argahv** [truedread/netflix-1080p#38]
The latest version 1.12 works fine with 1080p and 5.1 but after playing a while the audio and video get out of sync. The audio becomes faster than the video

**Comment by truedread** [comment]
Hmm, is this on all videos or a specific one? Also, try the newest release and see if it happens when selecting 2.0 audio.

**Comment by truedread** [comment]
Closing as major changes have been made that have probably fixed this.
