### ISSUE TITLE
I need the 2.0 sound by default.

### ISSUE THREAD

**Issue by AnubisMann** [truedread/netflix-1080p#40]
I need the 2.0 sound by default. Leave 5.1 as optional.

**Comment by scorpion421** [comment]
Don't demand anything. Gently ask for it. How about "please" and "Thank you in advance"?

**Comment by AnubisMann** [comment]
> Don't demand anything. Gently ask for it. How about "please" and "Thank you in advance"?

And what if I get paid to be a free guinea pig?

**Comment by truedread** [comment]
Added in latest release.
