### ISSUE TITLE
Donations without crypto currencies?

### ISSUE THREAD

**Issue by devkid** [truedread/netflix-1080p#41]
I'd like to buy you a coffee or two for this useful piece of software, but I despise crypto currencies for their senseless waste of electricity. Can I donate via some other way?

**Comment by fmorva** [comment]
https://hackernoon.com/the-bitcoin-vs-visa-electricity-consumption-fallacy-8cf194987a50

**Comment by devkid** [comment]
@fmorva Yeah mate, that doesn't help. (The article compares energy consumption of the whole banking system with that of bitcoin, not energy consumption per transaction. But I don't want to this discuss this here.)

**Comment by truedread** [comment]
If you have any other methods to suggest that carry some anonymity with it (i.e. not PayPal) that would be great. I just suggested cryptocurrency as it is a nice way to transfer funds with some semblance of anonymity. However, if it's too inconvenient to donate, don't worry about it.

**Comment by Cysioland** [comment]
https://ko-fi.com/ ?

**Comment by truedread** [comment]
https://ko-fi.com/truedread
