### ISSUE TITLE
Again, M7111-1309

### ISSUE THREAD

**Issue by LtqxWYEG** [truedread/netflix-1080p#42]
Getting this in console:
`index.js:173 Uncaught SyntaxError: Unexpected end of input
none:6 WebSocket connection to 'wss://push.prod.netflix.com/ws' failed: Error in connection establishment: net::ERR_CONNECTION_CLOSED
o.open @ none:6
o.addListener @ none:6
r @ none:6
i @ none:6
(anonymous) @ none:6
u @ none:6
(anonymous) @ none:6
a @ none:6
A @ none:6
(anonymous) @ none:7
require @ none:1
kickoff @ none:1
(anonymous) @ none:7
(anonymous) @ none:7
cadmium-playercore-6.0011.474.011-1080p.js:29434 Manifest locked to Edge (or not available in 1080p)
cadmium-playercore-6.0011.474.011-1080p.js:29435 Getting Edge manifest
VM68:199 Performing key exchange
VM68:201 Key exchange data:
VM68:202 {headerdata: {…}, encryptionKeyData: {…}, signKeyData: {…}}
VM68:92 Getting video metadata for ID 80219127
VM68:103 Metadata response:
VM68:104 {version: "2.1", video: {…}, trackIds: {…}}
none:6 WebSocket connection to 'wss://push.prod.netflix.com/ws' failed: Error in connection establishment: net::ERR_CONNECTION_CLOSED
o.open @ none:6
(anonymous) @ none:6
none:6 WebSocket connection to 'wss://push.prod.netflix.com/ws' failed: Error in connection establishment: net::ERR_CONNECTION_CLOSED
o.open @ none:6
(anonymous) @ none:6
none:6 WebSocket connection to 'wss://push.prod.netflix.com/ws' failed: Error in connection establishment: net::ERR_CONNECTION_CLOSED
o.open @ none:6
(anonymous) @ none:6
none:6 WebSocket connection to 'wss://push.prod.netflix.com/ws' failed: Error in connection establishment: net::ERR_CONNECTION_CLOSED
o.open @ none:6
(anonymous) @ none:6
none:6 WebSocket connection to 'wss://push.prod.netflix.com/ws' failed: Error in connection establishment: net::ERR_CONNECTION_CLOSED
o.open @ none:6
(anonymous) @ none:6
none:6 WebSocket connection to 'wss://push.prod.netflix.com/ws' failed: Error in connection establishment: net::ERR_CONNECTION_CLOSED
o.open @ none:6
(anonymous) @ none:6
`
![netflix 1080p error](https://user-images.githubusercontent.com/44180911/50486347-81258980-09f1-11e9-909e-f50b5317967e.png)

This issue has been closed: https://github.com/truedread/netflix-1080p/issues/20
So I'm opening a new one. :P 

I tried watching Avengers Infinity War: https://www.netflix.com/watch/0?origId=80219127 but it really happens on any big movie.
I deactivated all other Addons, restarted Chrome and then tried again with the same result. Deactivating your addon lets me watch the movie in horrible 480p. There are reasons why Chrome is the only option for me right now. :(
Looking at the log I assume this is the reason for the fail: 
> Manifest locked to Edge (or not available in 1080p)

regards

**Comment by qwert2812** [comment]
First time trying the addon. For me clicking on the extension doesn't even do anything. Am I doing something wrong?

**Comment by Hi1307** [comment]
> 
> 
> First time trying the addon. For me clicking on the extension doesn't even do anything. Am I doing something wrong?

It should automatically work, and if it doesn't Netflix will show an error.

**Comment by LtqxWYEG** [comment]
AFAIK, the key combination "CTRL+Shift+ALT+S" that brings a menu is from the extension, right? Because without the addon, the combination doesn't work. (Only "CTRL+Shift+ALT+D" works in vanilla Netflix, showing codec information)

**Comment by LtqxWYEG** [comment]
Seems to be fixed now.

**Comment by nyuszika7h** [comment]
> AFAIK, the key combination "CTRL+Shift+ALT+S" that brings a menu is from the extension, right? Because without the addon, the combination doesn't work. (Only "CTRL+Shift+ALT+D" works in vanilla Netflix, showing codec information)

It was a feature of Netflix itself, but it's no longer supported in the latest cadmium playercore, the addon brings it back.

**Comment by truedread** [comment]
Can you try this again with the new release?

**Comment by LtqxWYEG** [comment]
Ah, thanks! It works now! :)

Movies still only play in either 480p or 540p though. But I guess that can't be changed, right?

**Comment by truedread** [comment]
Unfortunately, no. I detailed why [here](https://github.com/truedread/netflix-1080p/releases/tag/v1.13).
