### ISSUE TITLE
Playercore updated again ;__;

### ISSUE THREAD

**Issue by Cysioland** [truedread/netflix-1080p#45]
cadmium-playercore-6.0012.078.011.js

**Comment by robbzor** [comment]
So I'm guessing that's what's causing the addon to not work correctly currently, right?

**Comment by AndroidFire9704** [comment]
> Don't know how new this is but 20th Century Fox TV shows, which for some reason have always been extra trouble compared to every other TV series, won't go above 480p/540p at the moment. Examples are How I Met Your Mother, Homeland, American Crime Story, American Horror Story.

their films also won't play more than 540p. Example: Deadpool.

**Comment by truedread** [comment]
Updated.
