### ISSUE TITLE
Please make a similar extension for Microsoft Edge

### ISSUE THREAD

**Issue by psvita123** [truedread/netflix-1080p#46]
Hello sir,
This is not an issue. I am just asking for a feature. You extension works perfectly on my chrome. I am able to get Full HD and also the bitrate secret menu with your extension. Netflix recently blocked the bitrate menu and only with your extension enabled i am able to get it(only God knows how you did that!!!).
The feature I am asking for is that can you make a similar extension for Microsoft Edge as I want to access the birtare menu in there. I want to watch 4k and meet all the requirements, but still netflix suddenly lowers the bitrate and I am not getting constant 4k bitrate. Sir, can you please make an extension for Edge that would bring back the bitrate menu please? That would be highly helpful.
I am very sorry if me asking about this over here upset you in any way sir. 
Thanks again for your marvelous Chrome extension.

**Comment by good4y0u** [comment]
Doesn't edge already do up to 4k, it could be your network speed.

**Comment by psvita123** [comment]
Yes edge supports 4k and I have high network speedas but every 10 minutes or so Netflix reduces the quality to 240p. Thats the reason i was asking for bitrate menu for edge so i can lock the bitrate to 4k bitrate

**Comment by AndroidFire9704** [comment]
what's your network speed?

**Comment by psvita123** [comment]
Around 40 mbps down and 10 mbps up

**Comment by good4y0u** [comment]
> Around 40 mbps down and 10 mbps up
Netflix speed requirement: "A steady internet connection speed of 25 megabits per second or higher. See below for more details. " -https://help.netflix.com/en/node/13444 and https://help.netflix.com/en/node/306 

What is your ping/ Latency, Could it be that your connection isn't stable at 40?   
My dad has a 100/100 connection but sometimes has reliability issues as it is a coax line from the ISP's local hub.

I'm going to be honest, to me those speeds seem slow, but where I am I have a residential fiber line.. so everything that isn't gig speeds seem slow.

**Comment by AndroidFire9704** [comment]
@psvita123 And which Components has your System??

**Comment by psvita123** [comment]
> > Around 40 mbps down and 10 mbps up
> > Netflix speed requirement: "A steady internet connection speed of 25 megabits per second or higher. See below for more details. " -https://help.netflix.com/en/node/13444 and https://help.netflix.com/en/node/306
> 
> What is your ping/ Latency, Could it be that your connection isn't stable at 40?
> My dad has a 100/100 connection but sometimes has reliability issues as it is a coax line from the ISP's local hub.
> 
> I'm going to be honest, to me those speeds seem slow, but where I am I have a residential fiber line.. so everything that isn't gig speeds seem slow

Good for you but I dont require such high speeds and as per netflix requirement a 25 mbps connection is required for 4k streaming so i can say that that requirement is not a problem to me.

**Comment by psvita123** [comment]
> @psvita123 And which Components has your System?? Is your Graphicscard a AMD or Nvidia one?

I7 700HQ 2.8 Ghz
Intel HD 630
16 Gb ram
Nvidia 1050 GPU
4 gb VRAM
got a 4k monitor
HDMI 2.2
as per all the Netflix requirement i have sufficient materials and i can watch 4k but i dont every once in a while the quality just goes from 4k to 240p, like maybe every 10 15 mins. Bit rate menu for me perfectly to solve this prob until some guy at Netflix thought "hey lets remove this feature!!!!!"

**Comment by good4y0u** [comment]
> > > Around 40 mbps down and 10 mbps up
> > > Netflix speed requirement: "A steady internet connection speed of 25 megabits per second or higher. See below for more details. " -https://help.netflix.com/en/node/13444 and https://help.netflix.com/en/node/306
> > 
> > 
> > What is your ping/ Latency, Could it be that your connection isn't stable at 40?
> > My dad has a 100/100 connection but sometimes has reliability issues as it is a coax line from the ISP's local hub.
> > I'm going to be honest, to me those speeds seem slow, but where I am I have a residential fiber line.. so everything that isn't gig speeds seem slow
> 
> Good for you but I dont require such high speeds and as per netflix requirement a 25 mbps connection is required for 4k streaming so i can say that that requirement is not a problem to me.
> FYI, my ping around 5, sometimes 4 but mostly 5

Are you using WIFI or are you hardwired with ethernet, and if you're on wifi does the issue go away if you hardwire? 

Run the netflix speedtest https://fast.com/ , that should test to netflix's servers specifically(its their service)   Hit the "show more info" option and let us know what that says.

**Comment by Essam315** [comment]
@psvita123
Try to ask the owner of this add-on, it works fine for me on Firefox.

https://addons.mozilla.org/en-US/firefox/addon/better-netflix/

**Comment by psvita123** [comment]
> @psvita123
> Try to ask the owner of this add-on, it works fine for me on Firefox.
> 
> https://addons.mozilla.org/en-US/firefox/addon/better-netflix/

yeah thats what i am trying to do.
it woorks perfectly on chrome as well, but sadly chrome and firefox do not support 4k streaming for netflix

**Comment by Essam315** [comment]
@psvita123
Install this add-on on Firefox

https://addons.mozilla.org/en-US/firefox/addon/better-netflix/

then install this one on Firefox

https://addons.mozilla.org/en-US/firefox/addon/uaswitcher/

and choose "Windows / Edge 17", and try some 4K movies and TV series, for me it plays 1080p and that is the most i can get, not sure if it will work for you or not.

**Comment by psvita123** [comment]
So 1080p works for you because you dont meet the 4k streaming conditions or
you do meet them but still firefox does not work for you for 4k

**Comment by vitorgrs** [comment]
Coming here to ask this too. Recently Netflix disabled ctrl+alt+shift+s menu. Right now it just works with this extension. I tried to port the extension to edge, but then Netflix didn't played anything... 
So welp!

I guess the bitrate menu just works for CrOS now?

**Comment by truedread** [comment]
Closed. Out of the scope of this extension. Please look towards forks.
