### ISSUE TITLE
No 5.1 and no more 1080p

### ISSUE THREAD

**Issue by Multipanda** [truedread/netflix-1080p#47]
Early this month the extension suddenly stopped working for me.
 The test pattern seems to still be working, but none of the movies and shows I checked out had 5.1 or 1080p, including some like Mars that worked fine last year.

The only indication that the extension is active to some degree is that it shows that the audio is 2.0 when watching something.
It's the same with vladikoff's version for Firefox.

**Comment by xf-** [comment]
duplicate - change @netflix

**Comment by NuclearCow** [comment]
Bumping this. I used to have 7k bitrate on BoJack and now it's not letting me choose that. Some other movies have ridiculously low bitrate like Sully. @truedread

**Comment by fengapappit** [comment]
Yep, I confirm.
It's now 480p tier streaming in most of the content.

**Comment by devkid** [comment]
Are there regional differences? I get 1080p right now in Germany on almost anything.

**Comment by Brandhand** [comment]
@devkid: Even on movies? I get eg "The Net" or "World War Z" only in 480p, "Kingsman" in 540p.
I think all Netflix productions are in 1080p. I'm on Linux/Chrome.

**Comment by devkid** [comment]
@Brandhand True, none of that is even 720p. I understood @NuclearCow's comment in a way that they don't have 1080p on Bojack, but I don't have 7k bitrate there as well (still 1080p though, never checked before for the bit rate).

You seem to be right that all Netflix productions are 1080p (but only with this addon enabled).

**Comment by fengapappit** [comment]
Well I had time to test.

Some content is available in 1080p, while some others are really bad, but disabling the extension doesn't seem to change that.

Here is an example with Nightflyers, the new Netflix Original, that you would expect to be 1080p :

![sc](https://user-images.githubusercontent.com/6908355/52535494-57c97e80-2d4f-11e9-8b66-3934dfe880b7.png)

This is the maximum quality that I can obtain on Chrome on Linux.

There is no error in console.

I don't know if that's something that the add-on can help with. I guess that the quality drop comes from the fact that Netflix detects that it's not Edge or Windows App, but I don't know.

**Comment by Brandhand** [comment]
Well, Nightflyer is not a true Netflix-Original, it's from SyFy, look it up.

**Comment by NuclearCow** [comment]
@devkid yeah it's still 1080p but higher bitrate is not available anymore

**Comment by chocoa510** [comment]
I'm still getting 1080p ( as of 14 Feb 2019)but NO 5.1 anymore.
I've tried all the flags to push it reported in any web searches.
eg --disable-audio-output-resampler  --try-supported-channel-layouts --force-wave-audio

no effect :(

**Comment by NuclearCow** [comment]
@chocoa510 thanks for the info.
Where did truedread go lol

**Comment by chocoa510** [comment]
@NuclearCow 
I recall truedread saying he is/was at college and this extension gets more and more complicated as Netflix play games. Respect to him for what he's achieved to date. Hopefully he will continue to develop this when time permits..

**Comment by ItsNickBarry** [comment]
The option for 5.1 audio has been moved to the extension's options menu.  Have you checked the box there?

**Comment by chocoa510** [comment]
@ItsNickBarry 
Thanks for that. I'll see how it goes. I just assumed Netflix was fiddling to keep Chrome the poor cousin so folk would accept locked down Edge or their App.
I don't recall that option either - 'always' had 5.1, so never looked. Shame on me.
Appreciate the head up!

**Comment by NuclearCow** [comment]
> @NuclearCow
> I recall truedread saying he is/was at college and this extension gets more and more complicated as Netflix play games. Respect to him for what he's achieved to date. Hopefully he will continue to develop this when time permits..

Almost forgot about that sry 😂

**Comment by truedread** [comment]
Should be fixed for now, give it another shot?
