### ISSUE TITLE
feature request: option to *not* enable 1080p [to allow 5.1 only]

### ISSUE THREAD

**Issue by sarangnemo** [truedread/netflix-1080p#49]
Thanks for your awesome work! I have a small but slightly odd feature request, given the title of your extension. :-) I'm probably not alone, but my sole reason for using the extension is actually to get 5.1. In my case, I can't really benefit from 1080p since I have a 720p projector as well as an older HTPC that gets choppy when trying to play the 1080p stream. (It's happy with the video stream chosen when the extension is disabled.) Of course, eventually it drops down to a stream my computer can handle, but it's distracting for the first minute or two every time.

**Comment by NuclearCow** [comment]
I think you can lower the amount of bitrate using ctrl shift alt s

**Comment by sarangnemo** [comment]
Yes, but it doesn't stick permanently, so you need to do it every time you start a movie/show.

**Comment by truedread** [comment]
I wouldn't consider this beneficial for the extension since it's named "netflix-1080p" and 5.1 was purely complementary. I may consider it in the future though.
