### ISSUE TITLE
Tons of movies aren't available in 1080p

### ISSUE THREAD

**Issue by NuclearCow** [truedread/netflix-1080p#50]
I tried with the extension but they're all only available in SD, e.g. Iron Man, Forrest Gump, Modern Family. They're all available in HD when I try to check it on Edge but with the extension it ain't workin.

**Comment by Essam31** [comment]
same here.

**Comment by ItsNickBarry** [comment]
See the latest [release notes](https://github.com/truedread/netflix-1080p/releases).
