### ISSUE TITLE
Quality eventually drops from 1080p

### ISSUE THREAD

**Issue by matthew-baker01** [truedread/netflix-1080p#51]
While watching quality eventually drops and I have to refresh to re-enable 1080p

**Comment by NuclearCow** [comment]
Haven't had this problem except on most movies and some TV shows like modern family don't have 1080p. They do on Edge tho...
Friggin Netflix playing tricks every time

**Comment by ItsNickBarry** [comment]
Use `ctrl` + `alt` + `shift` + `S` to access the bitrate menu and override automatic selection.

**Comment by matthew-baker01** [comment]
> Use `ctrl` + `alt` + `shift` + `S` to access the bitrate menu and override automatic selection.

This doesn't work anymore

**Comment by NuclearCow** [comment]
I think it still works with the plugin installed

**Comment by jLynx** [comment]
Yep, I am having the same issue. Its getting super annoying

**Comment by matthew-baker01** [comment]
Oh yeah, you're right, the plugin brings back ``ctrl alt shift s`` function. Thanks!

**Comment by jLynx** [comment]
That's strange. It doesn't work for me. Are you using Chrome Matthew?

**Comment by matthew-baker01** [comment]
Yeah, I'm using chrome.

**Comment by ExpensiveKoala** [comment]
I'm having this issue as well. The bitrate keeps defaulting to the lowest few. I don't want to have to manually override the bitrate every episode.

**Comment by ItsNickBarry** [comment]
@ExpensiveKoala I wrote a plugin to do this automatically for [netflix-1080p-firefox](https://github.com/vladikoff/netflix-1080p-firefox).  It can be found [here](https://github.com/ItsNickBarry/netflix-max-bitrate).  The code could be easily released as a Chrome extension.  But I don't work for Google.

**Comment by jLynx** [comment]
@ItsNickBarry you dont have to work for Google to release a Chrome extension. Anyone can do it.

**Comment by Syc0x00** [comment]
@jLynx I think his issue was more pricing.

**Comment by OscarVanL** [comment]
I had the exact same issue, I have made a fork that adds @ItsNickBarry's functionality into this plugin with an option in the extension options. (Disabled by default).

**Comment by OscarVanL** [comment]
Hi @matthew-baker01, could you test the newly merged commits (you will need to update the plugin from the source files and then enable the max-bitrate option in the plugin options) and see if it solves your issue? 

Then perhaps this issue can be closed if it does help.

**Comment by matthew-baker01** [comment]
It seems to have worked yeah! I'll close
