### ISSUE TITLE
Extension working but it only show low bitrate (I tried another movies)

### ISSUE THREAD

**Issue by waritxx** [truedread/netflix-1080p#52]
It shows only lower 1000 bitrate.
I tried play it on Edge. It showed 1080p.
![image](https://user-images.githubusercontent.com/18569094/54021886-befa1780-41c3-11e9-820e-45f967e70226.png)
![image](https://user-images.githubusercontent.com/18569094/54024069-32eaee80-41c9-11e9-90ee-25050df98840.png)

**Comment by NuclearCow** [comment]
Issue has been mentioned before. Most movies and TV shows that are not from Netflix don't have 1080p when using the plugin. Don't expect it to change as truedread is away for quite a while now and with Netflix playing dang tricks 🙄

**Comment by waritxx** [comment]
> Issue has been mentioned before. Most movies and TV shows that are not from Netflix don't have 1080p when using the plugin. Don't expect it to change as truedread is away for quite a while now and with Netflix playing dang tricks 🙄

Thank you! I try to play a TV show from Netflix. It show bitrate list properly!

**Comment by truedread** [comment]
let's try again?
