### ISSUE TITLE
Errors when embedded in an iframe

### ISSUE THREAD

**Issue by gurupras** [truedread/netflix-1080p#53]
I run a [website](https://twoseven.xyz) that enables people to watch together videos from content providers like Netflix/Amazon/YouTube/etc. We do this  by using a Chrome extension to embed these websites within an iframe and then set up listeners for play, pause and seek.

Recently, I had a user report that our extension does not play along nicely with yours. After looking into it for a while, I've realized that the issue is not to do with conflicts between extensions, but the fact that this extension fails when Netflix is embedded in an iframe.

At this point, the only anomaly I've found is that the cadmium-playercore version that Netflix is serving is different from the one being injected in via this extension.

<pre>
<b>Request URL</b>: https://assets.nflxext.com/en_us/ffe/player/html/cadmium-playercore-6.0012.829.011.js
<b>Request Method</b>: GET
<b>Status Code</b>: 307 Internal Redirect
<b>Location</b>: chrome-extension://cankofcoohmbhfpcemhmaaeennfbnmgp/cadmium-playercore-6.0011.853.011-1080p.js
<b>Non-Authoritative-Reason</b>: WebRequest API
</pre>

Eventually, when you try to play a video, it results in an error with code `M7111-1003`.

Is there any reason you can think of as to why this extension would begin to fail when embedded in an iframe? If this is an insurmountable technical limitation, could I make a request to restrict the extension to only work only in cases where Netflix is the top frame (`window.top === window`)? I can certainly help make a PR for this if needed.

To reproduce this error, I've set up a [pen](https://codepen.io/gurupras/pen/LajXLe) with an embedded Netflix. Please note that you will need an extension to modify the `x-frame-options` header when attempting to reproduce this.

**Comment by ItsNickBarry** [comment]
Try running this fork with your site:
https://github.com/ItsNickBarry/netflix-1080p

I can't account for the Netflix error code, but this should inject the modified `cadmium-playercore` into the iframe.  I'll submit a pull request if it works.

**Comment by gurupras** [comment]
Yup. Seems to work fine. 
Ah, I see what's happening. I was thinking `all_frames` defaults to true which is why it was not included in the manifest. Turns out the background script was removing cadmium player and the  content-script was not including one since it was iframed.

**Comment by ItsNickBarry** [comment]
I've submitted a pull request; however, this project has been mostly inactive since Netflix broke most of its functionality.  You might want to direct your users towards the fork, or publish your own version.

I've submitted a pull request to the [Firefix version](https://github.com/vladikoff/netflix-1080p-firefox/pull/25) as well.

**Comment by truedread** [comment]
merged! thanks @ItsNickBarry

**Comment by mageshr26** [comment]
> 
> 
> I run a [website](https://twoseven.xyz) that enables people to watch together videos from content providers like Netflix/Amazon/YouTube/etc. We do this by using a Chrome extension to embed these websites within an iframe and then set up listeners for play, pause and seek.
> 
> Recently, I had a user report that our extension does not play along nicely with yours. After looking into it for a while, I've realized that the issue is not to do with conflicts between extensions, but the fact that this extension fails when Netflix is embedded in an iframe.
> 
> At this point, the only anomaly I've found is that the cadmium-playercore version that Netflix is serving is different from the one being injected in via this extension.
> 
> Request URL: https://assets.nflxext.com/en_us/ffe/player/html/cadmium-playercore-6.0012.829.011.js
> Request Method: GET
> Status Code: 307 Internal Redirect
> Location: chrome-extension://cankofcoohmbhfpcemhmaaeennfbnmgp/cadmium-playercore-6.0011.853.011-1080p.js
> Non-Authoritative-Reason: WebRequest API
> 
> Eventually, when you try to play a video, it results in an error with code `M7111-1003`.
> 
> Is there any reason you can think of as to why this extension would begin to fail when embedded in an iframe? If this is an insurmountable technical limitation, could I make a request to restrict the extension to only work only in cases where Netflix is the top frame (`window.top === window`)? I can certainly help make a PR for this if needed.
> 
> To reproduce this error, I've set up a [pen](https://codepen.io/gurupras/pen/LajXLe) with an embedded Netflix. Please note that you will need an extension to modify the `x-frame-options` header when attempting to reproduce this.

HI,
Can you help me to load netflix inside iframe..I tried in may ways...Kindly help me with this..Thanks in advance
