### ISSUE TITLE
Some shows don't work?

### ISSUE THREAD

**Issue by spiindex** [truedread/netflix-1080p#55]
Hi there,

first: really great extension! I would die without it.
But, is there any reason why it doesn't work on some shows/movies?

Family Guy isn't working in 1080p but other shows like Bojack Horseman and Rick and Morty are working.
![image](https://user-images.githubusercontent.com/37789508/55435033-4fe0ca80-5599-11e9-82a4-faba84234be9.png)
![image](https://user-images.githubusercontent.com/37789508/55435043-53745180-5599-11e9-9d69-2c5529b626ed.png)

**Comment by ItsNickBarry** [comment]
See the release notes for the latest version.

**Comment by ItsNickBarry** [comment]
[here](https://github.com/truedread/netflix-1080p/releases)

**Comment by truedread** [comment]
can try now

**Comment by JunnanZ** [comment]
Similar issue happens to me. It doesn't work on The Last Kingdom or Parks and Recreation.
