### ISSUE TITLE
higher bitrate

### ISSUE THREAD

**Issue by armin884** [truedread/netflix-1080p#56]
On Edge i get Bitrate: 5110kbps - Profile: playready-h264mpl40-dash.
On Chrome i only get Bitrate: 2023 Profile: playready-h264hpl40-dash with the same movie.

No longer possible to get higher bitrates on chrome? Already read release notes for the latest version, is that problem not solved yet?

**Comment by NuclearCow** [comment]
Netflix messed things up. It's harder to unlock the bitrate now

**Comment by armin884** [comment]
Thanks, if its harder you know how to do? Changing just the ESN doesn't work anymore...

**Comment by truedread** [comment]
try now?
