### ISSUE TITLE
[Issue] Edge Chromium Bitrate lower

### ISSUE THREAD

**Issue by Jowat97** [truedread/netflix-1080p#57]
There is a new Edge Browser running with Chromium Engine. (https://www.microsoftedgeinsider.com/en-us/)
4K Netflix works with it, but with this Addon I only get 1080p. The Reason why I need this Addon is for the Bitrate Menu and 5.1 Audio.
Is there a way to get the Bitrate Menu and 5.1 only without forcing 1080p? So people with Edge Chromium could get 4K Netflix with Bitrate Menu.

**Comment by psvita123** [comment]
please i want same exact thing

**Comment by truedread** [comment]
this extension really isn't suited for that but i could look into making another branch?

**Comment by Jowat97** [comment]
> this extension really isn't suited for that but i could look into making another branch?

This would be really amazing! Since Netflix removed the Bitrate-menu, it is not possible to change the quality manually. Because Edge-Chromium already supports up to 4k, there is no need for the "1080p function" of this AddOn. If you want you can add 5.1 or 7.1 Audio for the Edge-Branch, but I think the most important thing for the most people, also for me is the Bitrate-menu. 😄

**Comment by Valentin144** [comment]
Yes please, that would be awesome.

**Comment by Jowat97** [comment]
Hey there, I do not want to be impatient or intrusive but is there any progress so far? This Issue is already half a year old. Chromium Edge is pretty dope so far and has a huge community.  Microsoft wants to add 4K DRM also to the Chromium Project, so other Chromium based Browsers like Google Chrome, Opera, Brave etc. would also play 4K content from Netflix in near feature: https://www.windowslatest.com/2019/09/02/drm-4k-media-support-in-chromium-for-windows/
So, this "4K-Externsion" could be useful for those browsers aswell. Thanks for your work so far!

**Comment by Jowat97** [comment]
There is a fork for edge now: https://github.com/lkmvip/netflix-4K-DDplus
Consider this issue as closed. Thanks.
