### ISSUE TITLE
Extension stopping netflix from working

### ISSUE THREAD

**Issue by TODO4EVER** [truedread/netflix-1080p#60]
Hello, 
I had this problem for like 1 hour now, I can't play anything on chrome with this extension, used to work perfectly.
I get this error [](https://i.imgur.com/FJF4bNA.png)
When I disable the extension everything runs fine with terribly low resolution and bitrate : (

**Comment by truedread** [comment]
Try latest commit?

**Comment by Matthius453** [comment]
Hi, if this helps the developer, chrome keeps pulling up these errors with the latest commit (11 hours ago)
Uncaught TypeError: Cannot read property 'SU' of undefined (on line 36391)

**Comment by Matthius453** [comment]
> Try latest commit?
Just refreshed the Code page and saw your latest update of the playercore a few minutes ago. This seems to work fine, thanks!

**Comment by TODO4EVER** [comment]
> Try latest commit?

Thank you very much! It is working now! 
sry I just realized the imgur photo I linked wasn't posted :D first time here :D
Thanks again!
