### ISSUE TITLE
v1.16,  5.1 audio not work

### ISSUE THREAD

**Issue by lkmvip** [truedread/netflix-1080p#61]
v1.16,  5.1 audio not work

**Comment by truedread** [comment]
logs? platform?

**Comment by lkmvip** [comment]
[20190721184319.all.log](https://github.com/truedread/netflix-1080p/files/3414502/20190721184319.all.log)



windows 10

**Comment by truedread** [comment]
What's in the console log?

**Comment by lkmvip** [comment]
cadmium-playercore-6.0015.328.011-1080p.js:55487 Manifest is not Edge locked, not doing anything
cadmium-playercore-6.0015.328.011-1080p.js:46069 [Violation] 'setTimeout' handler took 118ms
none:13 [Violation] 'setTimeout' handler took 59ms

**Comment by truedread** [comment]
Should be fixed in the latest commit.
