### ISSUE TITLE
Unexpended Error(opera&win) 1.14&1.15 

### ISSUE THREAD

**Issue by Kn0axTR** [truedread/netflix-1080p#63]
O7111-1003 error code and i try look console and i see 
```
chrome-extension://nmfikcpmiiikoaokjcpjngkbandapkcp/get_manifest.js net::ERR_FILE_NOT_FOUND
(anonymous) @ content_script.js:43

```
Before i installed 1.13 and thats work perfectly.

**Comment by truedread** [comment]
Update to the latest version.

**Comment by Kn0axTR** [comment]
i tried already lastest version not work with opera

**Comment by truedread** [comment]
Closing as major changes have been made that have probably fixed this.
