### ISSUE TITLE
Now it's not working now. 

### ISSUE THREAD

**Issue by waritxx** [truedread/netflix-1080p#65]
![Untitled](https://user-images.githubusercontent.com/18569094/61924365-9ff0fc00-af91-11e9-86cb-c1b9ae1853cf.png)

**Comment by lkmvip** [comment]
use v1.13

**Comment by waritxx** [comment]
![Screenshot_5](https://user-images.githubusercontent.com/18569094/61925105-f4e24180-af94-11e9-8f66-10997c1553ce.png)
Hmmm.

**Comment by lkmvip** [comment]
https://github.com/truedread/netflix-1080p/issues/64#issuecomment-515183312

**Comment by waritxx** [comment]
Thank you <3
![unknown](https://user-images.githubusercontent.com/18569094/61926893-c8322800-af9c-11e9-9471-df5c7cca6b10.png)

**Comment by iWajdi** [comment]
> ![Screenshot_5](https://user-images.githubusercontent.com/18569094/61925105-f4e24180-af94-11e9-8f66-10997c1553ce.png)
> Hmmm.

I will help you! Instead of draging it to install open this link " https://robwu.nl/crxviewer/ " upload the crx file to it, and downlaod the source files, so after that unzip the downloaded archive and enable developer tool in chrome and then click on load unpacked, and chose the unzipped folder, thats how you get it working

**Comment by iWajdi** [comment]
Thank you sooooo much for making it work I have the 1.18 Version and now it works like charm.

![image](https://user-images.githubusercontent.com/53441582/62061992-1d31a080-b220-11e9-9342-c7185356a2c4.png)

**Comment by waritxx** [comment]
but 1.18 doesn't support  5.1 option. 1.13 is better.

**Comment by iWajdi** [comment]
I honestly don't know whats the difference  I'd like to know but I don't
think I will notice an effect even tho I force enables it on my behalf
because I have a normal budget laptop with minimal stuff so I don't bother,
but fill me in with the news

**Comment by truedread** [comment]
Closing as major changes have been made that have probably fixed this.
