### ISSUE TITLE
v 1.18 no 5.1 audio

### ISSUE THREAD

**Issue by ShadyWorld** [truedread/netflix-1080p#66]
Thanks for the quick update! I have the 1080p working but can't get the 5.1 audio, is it just me?

**Comment by lkmvip** [comment]
use v1.13

**Comment by ShadyWorld** [comment]
even 1.13 I get 2.0 audio

**Comment by lkmvip** [comment]
![111](https://user-images.githubusercontent.com/12974141/62178703-97773780-b37c-11e9-9cfd-33117f7734a3.png)

**Comment by lianshun99** [comment]
用了1.13还是不出来5.1的选项   即使设置了也没有

**Comment by TheW0LVERIN3** [comment]
1.18 doesn't have any 5.1 audio either on macos but I am pretty sure it does have 1080p

**Comment by truedread** [comment]
Closing as major changes have been made that have probably fixed this.
