### ISSUE TITLE
This extension is not listed in the Chrome Web Store and may have been added without your knowledge. Learn more

### ISSUE THREAD

**Issue by killerqueen619** [truedread/netflix-1080p#67]
This extension is not listed in the Chrome Web Store and may have been added without your knowledge. Learn more

https://i.imgur.com/FDHoJNd.png

i try other versions stil same result in google chrome on windows 10

i try on 1.13 and 1.18

**Comment by TheW0LVERIN3** [comment]
It is just to warn you because other programs can install extensions on chrome and don't always ask permission. It gets displayed for every extension not installed from the chrome web store.

**Comment by asemarafa** [comment]
I think the quetsion here should be, why is the extension is no longer in the chrome store? should we expect it to be back soon?

https://chrome.google.com/webstore/detail/netflix-1080p/cankofcoohmbhfpcemhmaaeennfbnmgp

**Comment by ItsNickBarry** [comment]
@asemarafa The Firefox port was removed in June because it contained code owned by Netflix.  It seems likely that the same thing happened here.

**Comment by tomty89** [comment]
The extension stopped working here since at least today anyway. Netflix has gone blurry again.

**Comment by killerqueen619** [comment]
> It is just to warn you because other programs can install extensions on chrome and don't always ask permission. It gets displayed for every extension not installed from the chrome web store.

but the problem i cannot enable it
still disabled.

**Comment by asemarafa** [comment]
@killerqueen619 You can't enable it in chrome anymore thats been thier policy for a while.
An alternative is to clone the repo and load as unpacked extension

**Comment by T4iga** [comment]
Guys, try the steps posted in the following issue by @jaagupku 
https://github.com/truedread/netflix-1080p/issues/68#issuecomment-517929484

**Comment by ghftred** [comment]
> The extension stopped working here since at least today anyway. Netflix has gone blurry again.

its able to play but blurry? not the "cant stream instantly "error?

**Comment by tomty89** [comment]
@ghftred yeah that's what happened here on Linux

**Comment by TheW0LVERIN3** [comment]
On macos too

**Comment by truedread** [comment]
Currently working on trying to get this back on the store.

**Comment by truedread** [comment]
Right now it's under review. Who knows how long it could take, but Google hasn't been very kind to me with this extension.

**Comment by truedread** [comment]
Extension has been rejected numerous times, but I will keep trying.

**Comment by vegardheimdal** [comment]
> Extension has been rejected numerous times, but I will keep trying.

Is there any way to actually use the extension, unless it's in the store?

**Comment by truedread** [comment]
> > Extension has been rejected numerous times, but I will keep trying.
> 
> Is there any way to actually use the extension, unless it's in the store?

Yes there is. I upload packed .crx versions of the extension on the Releases page, and you can turn on Developer mode in chrome://extensions and then drag and drop the .crx file onto the page to install it.

**Comment by vegardheimdal** [comment]
> > > Extension has been rejected numerous times, but I will keep trying.
> > 
> > 
> > Is there any way to actually use the extension, unless it's in the store?
> 
> Yes there is. I upload packed .crx versions of the extension on the Releases page, and you can turn on Developer mode in chrome://extensions and then drag and drop the .crx file onto the page to install it.

Installing it works with Developer mode switched on, true.
But recently even once installed it is no longer possible to enable the addon.

There's a 'Learn more' link to click on, which says:

"Extensions disabled by Chrome
The information below applies to users on Windows and Mac only.

If you see a message saying "Extensions Disabled," it's because Chrome has turned off one or more of your extensions to keep your data safe while you're browsing the Internet.

The extensions that Chrome turned off either didn't come from the Chrome Web Store or were determined unsafe."

**Comment by truedread** [comment]
Well guess what. The extension is now available on the Chrome webstore! The link in the README still works, so please install from there!

**Comment by abaynp** [comment]
in case of this amazing extension get kicked again from chrome webstore. simply download the crx file from [here](https://github.com/truedread/netflix-1080p/releases).
Download it with external download manager like IDM. Do not use built in chrome-based browser downloader, the file will immediately deleted.
Set Extensions Manager to developer mode
Drag the crx file to extensions manager windows, the Netflix 1080p extension would be installed but not enabled.
Click on Netflix 1080p extension, add get the extension ID
open regedit
Then add the following string in these keys (make it if there's none)
[HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Edge\ExtensionInstallAllowlist]
[HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome\ExtensionInstallAllowlist]
add strings
"1"="Netflix1080PextensionID"
"2"="anotherblockedextensionIDyouwanttoenable"
hope this help.
