### ISSUE TITLE
Doesn't work anymore 

### ISSUE THREAD

**Issue by Oravore** [truedread/netflix-1080p#68]
![chrome_2019-08-03_14-29-07](https://user-images.githubusercontent.com/53163479/62410721-2b563700-b5fb-11e9-9a7f-3d8cd288e829.png)
![chrome_2019-08-03_14-28-53](https://user-images.githubusercontent.com/53163479/62410722-2beecd80-b5fb-11e9-88b7-32424b59ea6c.png)

**Comment by jaagupku** [comment]
You should try the new 1.18 version, it works for me.

**Comment by Oravore** [comment]
sweet how would I install it now that it's not on the chrome store?

**Comment by jaagupku** [comment]
Okay,

1. Go to `chrome://extensions/`
2. Enable `Developer mode`, top right corner
3. Download latest version from releases here on github (Code -> Releases). It is .crx file
4. Unzip .crx file. For example with 7zip windows context menu option `Extract to "netflix1.18"`
5. In chrome extensions settings, click `Load Unpacked`
6. Select unpacked .crx folder.
7. You are good to go.

**Comment by Litca** [comment]
I tried now with the 1.18 release and manual installation but it seems doesn't work anymore. It is possible?

I'm on linux by the way and use Chrome 76.0.3809.87 64bit

**Comment by Brandhand** [comment]
It's not working for me either. I'm also using Linux/Chrome. Probalbly a country thing? I'm from germany

**Comment by T4iga** [comment]
Windows user with Brave (modified chromium) here. Thanks for the fix. Works flawlessly on my end with the guide provided by @jaagupku

**Comment by Litca** [comment]
Ok, guys, I just tried the extension in a virtual machine with Windows 7 64bit and latest Chrome release and it works! So, I think it's a problem with Linux, like the same issue we have with Amazon Primevideo (only sd) :'(

**Comment by killerqueen619** [comment]
> Okay,
> 
> 1. Go to `chrome://extensions/`
> 2. Enable `Developer mode`, top right corner
> 3. Download latest version from releases here on github (Code -> Releases). It is .crx file
> 4. Unzip .crx file. For example with 7zip windows context menu option `Extract to "netflix1.18"`
> 5. In chrome extensions settings, click `Load Unpacked`
> 6. Select unpacked .crx folder.
> 7. You are good to go.
> 
> But you may have to re-enable extension every time to open chrome.

worked very well
thank u!

**Comment by michael1011** [comment]
Version 1.18 doesn't work for me on Linux anymore neither. Any plans on updating this extension @truedread?

**Comment by rdmasio** [comment]
1.18 **working** at MacOS (10.13.6) Chrome (75.0.3770.142). Ty guys!

**Comment by Dragonisser** [comment]
Works fine on Windows 10 (1903) Chrome (76.0.3809.100)

**Comment by Litca** [comment]
Now ti works fine also on Linux. Thanks!!!

**Comment by TheW0LVERIN3** [comment]
Some better installation instructions,

1. Go to chrome://extensions/
2. Enable Developer mode, top right corner
3. Download latest version from releases here on github (Code -> Releases). It is .crx file
4. Drag the .crx file in the chrome://extensions/ tab
5. Click add extension
6. It should be added and good to go.

**Comment by leeterry** [comment]
@TheW0LVERIN3 Tried that 1st and it installed but the extension was disabled by default. So, I tried enabling it in chrome while dev mode was on and was unable to do it (even restarting chrome did not help). The instructions from @jaagupku worked fine though and after further research I may have found out why. From what I have read the instructions from @TheW0LVERIN3 will only work in dev versions of chrome (you install this extension that way it will auto disable itself leaving you with no way to enable it) but the ones @jaagupku posted should work in any version of chrome.

**Comment by leeterry** [comment]
Okay, to do this you 1st need to download the .crx version of this extension and then follow the instructions given above by [@TheW0LVERIN3](https://github.com/truedread/netflix-1080p/issues/68#issuecomment-524074462). Once that is finished and it is installed you need to locate/open the extensions folder for your chrome profile [this site will tell you how](https://stackoverflow.com/questions/10269002/where-does-google-chrome-store-unpacked-extensions). After you have opened the extensions folder you need to open the folder for this extension which for me was labeled 
`lmahkcmhdgieokglbknkfeplpfeonpol` 
but if you can not find that folder try reinstalling the extension in chrome while making a note of what the time is and then sorting the folders for the extensions by when they were modified. Anyway, once you found the folder for the extension open it and you should see a folder labeled 1.18 (the current version of the extension). That is the unpacked version of the extension that chrome made when it installed it. Now go back to chrome and install the unpacked extension in that folder by following the instructions above by [@jaagupku](https://github.com/truedread/netflix-1080p/issues/68#issuecomment-517929484). If done correctly it should now act more like it did before but you will still have to deal with the small popup every time chrome starts.

**Comment by alexey-sh** [comment]
it seems like it's possible through zip file only. but a crx approach still works on opera

**Comment by truedread** [comment]
Closing as major changes have been made that have probably fixed this.
