### ISSUE TITLE
1080p play not working on Avengers in Taiwan region

### ISSUE THREAD

**Issue by 29988122** [truedread/netflix-1080p#7]
PC, windows 10, latest ver of both chrome and firefox

[www.netflix.com-1522163440899.log](https://github.com/truedread/netflix-1080p/files/1852550/www.netflix.com-1522163440899.log)
Here's the console log if it helps..

Of course I've deleted the cache and cookies from chrome.

Thank you for this addon!

**Comment by Cysioland** [comment]
Also on Vaiana in Poland region

**Comment by truedread** [comment]
Is this with the beta branch?

**Comment by truedread** [comment]
Try it out with the latest version, and reopen if it still doesn't work.
