### ISSUE TITLE
Chrome Webstore link 404

### ISSUE THREAD

**Issue by thetruechar** [truedread/netflix-1080p#72]
https://chrome.google.com/webstore/detail/netflix-1080p/cankofcoohmbhfpcemhmaaeennfbnmgp

**Comment by OscarVanL** [comment]
Releases can be downloaded [here](https://github.com/truedread/netflix-1080p/releases), download the .crx file and then extract it with the zip tool of choice (eg: 7zip). In Chrome go to (Top right menu button) -> More Tools -> Extensions -> Load Unpacked (You need to toggle the Developer Mode setting in the top right first). Then load the folder that the .crx extracted to.

**Comment by dgw** [comment]
Duplicate of #67.

**Comment by thetruechar** [comment]
> Releases can be downloaded [here](https://github.com/truedread/netflix-1080p/releases), download the .crx file and then extract it with the zip tool of choice (eg: 7zip). In Chrome go to (Top right menu button) -> More Tools -> Extensions -> Load Unpacked (You need to toggle the Developer Mode setting in the top right first). Then load the folder that the .crx extracted to.
It works like a charm. BTW in Mac, you can use http://crxextractor.com/ to extract crx.
