### ISSUE TITLE
Why freeze watching with this add-on ?

### ISSUE THREAD

**Issue by tmac21** [truedread/netflix-1080p#73]
I love this app but always it's freeze while I watching videos and I stopped to use. Not stable like mic edge browser.

**Comment by OscarVanL** [comment]
It's probably this DRM-related issue: https://github.com/truedread/netflix-1080p/issues/15

Basically, all frames are being decoded without any hardware acceleration. This can cause dropped frames and perhaps freezing, as well as higher than usual CPU usage.

**Comment by truedread** [comment]
Closing as major changes have been made that have probably fixed this.
