### ISSUE TITLE
I can't change quality, only up to 495

### ISSUE THREAD

**Issue by Geniusssmit** [truedread/netflix-1080p#74]
Why I can't set quality higher than 495? 
![image](https://user-images.githubusercontent.com/24941285/65945187-18fe4b00-e43c-11e9-9339-025c60e7c78f.png)

**Comment by gyeongja** [comment]
same for me. most shows are getting way lower bitrate comparing edge and windows app even though both get same res 1080P

**Comment by tomty89** [comment]
It seems that the extension only works for Netflix Originals and so.

**Comment by Geniusssmit** [comment]
> It seems that the extension only works for Netflix Originals and so.

Wow, I guess Netflix forces us to use Edge in the end

**Comment by illuminati1337** [comment]
> > It seems that the extension only works for Netflix Originals and so.
> 
> Wow, I guess Netflix forces us to use Edge in the end

The new good Chromium Edge that works on Windows 7 also doesnt support 1080p

**Comment by lkmvip** [comment]
This is because of DRM, Windows 7 does not have DRM, and DRM was introduced after Windows 8. So the best viewing environment on Windows is WIN8 and above and EDGE or NetflixAPP.

And Windows10 is a more stable version of win8, so now basically use Windows10

and use edge not  Chromium Edge

**Comment by truedread** [comment]
Closing as major changes have been made that have probably fixed this.
