### ISSUE TITLE
Stopped working again

### ISSUE THREAD

**Issue by Showryuken** [truedread/netflix-1080p#75]

**Comment by 161134050** [comment]
same

**Comment by falcon78** [comment]
Same here

**Comment by NuclearCow** [comment]
Same here as well. Got the error code D7121-1331. Seems like Netflix screwed us over again.

**Comment by falcon78** [comment]
They played us like a damm fiddle

**Comment by hairycheez** [comment]
works on mac

**Comment by loveyoursupport** [comment]
> 
> 
> It works fine on linux, and fails on windows.

Damn , what the issue :(

**Comment by truedread** [comment]
Closing as major changes have been made that have probably fixed this.
