### ISSUE TITLE
Stopped working several weeks ago (Error Code: D7121-1331)

### ISSUE THREAD

**Issue by DiskuSystem** [truedread/netflix-1080p#77]
Edit: I'm on Microsoft Edge Dev, by the way. 

Hi.

I'm a huge fan of this extension and the work that has been put into it, it has improved my viewing experience the past year tremendously. But for the past week it has not been working and i haven't heard a word from the developer and i would just like to know if this extension is still being worked on and if there is a fix coming. I have been using the latest version available on GitHub. 

Thank you. 

Error code: Error Code: D7121-1331

**Comment by Cysioland** [comment]
Developer seems to have gone AWOL, sadly. The Kodi plugin works better, though still not perfectly.

I feel like at this point Netflix just won.

**Comment by Delivator** [comment]
Are you using [v1.19](https://github.com/truedread/netflix-1080p/tree/v1.19)?
Still works fine for me!

**Comment by DiskuSystem** [comment]
> Are you using [v1.19](https://github.com/truedread/netflix-1080p/tree/v1.19)?
> Still works fine for me!

Yes, i am and i forgot to mention that i'm on Microsoft Edge Dev as well.

**Comment by Delivator** [comment]
Have you tried it with chrome? I don't think Edge is supported.

**Comment by Cysioland** [comment]
@Delivator Tried your fork and on some shows I get 1080p, but on some still bitrate is below 1000.

**Comment by Delivator** [comment]
@Cysioland I haven't really chanaged anything in my fork. My goal was to convert this extention to a userscript so you can install it with tempermonkey. But I quickly ran intro problems and pretty much gave up 😅

**Comment by sidchh91** [comment]
any way to read manifests file from the latest version?

**Comment by hasufell** [comment]
This extension is gone from the webstore https://chrome.google.com/webstore/detail/netflix-1080p/cankofcoohmbhfpcemhmaaeennfbnmgp

Manual installation doesn't work anymore due to "CRX_REQUIRED_PROOF_MISSING".

**Comment by Delivator** [comment]
Yes it is gone from the chrome webstore.
No manual installation still works fine, just tested it with the newest version of chrome.
1080p also still works: https://i.imgur.com/9Fe3yxX.jpg

Just download the [latest release](https://github.com/truedread/netflix-1080p/releases/latest), extract the extention file like a zip archive, go to chrome://extensions/, enable delevoper mode and install the unpacked extention.

**Comment by Cysioland** [comment]
@Delivator 1080p works, but the bitrate is abysmal. In the good old days of the extension working it gave me bitrates up to 5900 kbps.

**Comment by truedread** [comment]
Closing as major changes have been made that have probably fixed this.
