### ISSUE TITLE
Dimmed Image when subtitles appear.

### ISSUE THREAD

**Issue by rapito** [truedread/netflix-1080p#78]
Watch any title and wait for it to go up to the highest resolution and all GUI disappears.
When subtitles appear and disappear, the brightness changes.

**Comment by truedread** [comment]
Closing as major changes have been made that have probably fixed this.

**Comment by rapito** [comment]
> Closing as major changes have been made that have probably fixed this.

I haven't checked in a while, will test and report back

**Comment by rapito** [comment]
works like a charm :D
