### ISSUE TITLE
How to install this extenstion ?

### ISSUE THREAD

**Issue by Mistercroquant** [truedread/netflix-1080p#79]
Hello all,
Since the official extension has been removed from the chrome store, how do you do to install the extenstion ? I already downloaded the files in my computer in zip format, what should I do next ?
Thanks.

**Comment by shaffyx** [comment]
I'm confused aswell. I can't find any instructions.

**Comment by TyrionGraphiste** [comment]
[](https://github.com/truedread/netflix-1080p/issues/77#issuecomment-569503867)

**Comment by fenryxo** [comment]
1. Unzip the extension.
2. Go to `chrome://extensions/`.
3. Toggle *Developer mode* on in the top right corner.
4. Click *Load unpacked* and choose the extension directory.

**Comment by awhorsky** [comment]
It gives me an error saying, "Manifest file is missing or unreadable"

**Comment by otakucordobez** [comment]
> 1. Unzip the extension.
> 2. Go to `chrome://extensions/`.
> 3. Toggle _Developer mode_ on in the top right corner.
> 4. Click _Load unpacked_ and choose the extension directory.

Thx for the explanation, was going crazy trying to know how to install it.

**Comment by truedread** [comment]
Closed.
