### ISSUE TITLE
Unexpected error requires Refresh to fix

### ISSUE THREAD

**Issue by ryanmusante** [truedread/netflix-1080p#8]
1080P functionality is good however with loading browser and running Netflix first time, error is always encountered and must be bypassed. Seen with most recent Chrome extension update.
```
Whoops, something went wrong...
Unexpected Error
Error Code: M7111-1331-4027
```

**Comment by AuroraWright** [comment]
Can confirm. It seems to occur the first time you play a given content; pausing playback and continuing it at a later date, or playing any subsequent episodes if it's a series, this doesn't happen.

**Comment by truedread** [comment]
I really don't know what's causing this. The manifest acquisition process in itself is a hack; I can try to refine it in my free time and see what's causing the bug but honestly, I think it's just some random async functions getting ahead of each other when they shouldn't be.

**Comment by truedread** [comment]
I fixed this in the latest update by automatically refreshing the page when it encounters an error, but I want to get it to a point where the error is never even encountered. Closing for now.

**Comment by ryanmusante** [comment]
Fantastic, thank you!
