### ISSUE TITLE
Can you add option for Dolby Digital Plus?

### ISSUE THREAD

**Issue by cemalgulbeyaz** [truedread/netflix-1080p#80]
5.1 works fine but it has only 192Kbps is there any way for higher bitrate and maybe Dolby Digital Plus for higher 640Kbps?

**Comment by Cysioland** [comment]
The author of this extension disappeared

**Comment by truedread** [comment]
no I didnt

**Comment by Cysioland** [comment]
I'm glad you're alive @truedread. Long time no see. But why‽

**Comment by cemalgulbeyaz** [comment]
> 
> 
> no I didnt

Hi, i installed the plugin and activated. After 5.1 sounds are come to list. Its cool. But if i check the bitrate list (Ctrl+Shift+Alt+S), there is only 192Kbps value even this Variable AAC codec. But FlixGrab+ or etc. programs can list many option for audio codec and bitrate. Is it possible for your plugin?

**Comment by hectorevil** [comment]
its possible to add more bitrate for audio instead 192Kbps?

**Comment by truedread** [comment]
Chrome does not support decoding Dolby Digital or Dolby Digital Plus to my knowledge, so I cannot add it to the extension. As for AAC, 128kbps is the highest bitrate Netflix offers unfortunately.
