### ISSUE TITLE
Ultra low bitrate 1080p VP9 on many titles.

### ISSUE THREAD

**Issue by NovaPrima** [truedread/netflix-1080p#82]
It's been this way for about three months. I hadn't bothered posting because it seemed truedread was MIA. Seems to be mainly, but not entirely, with newer stuff. One example is episode 202 of The End of the Fxxxing World. 201 is around 3Mbps, but 202 is sub-1Mbps. Edge plays it in AVC with a much higher bitrate. There are countless other examples. Try a random episode of a random recent show.

**Comment by Cysioland** [comment]
Same here.

I think that truedread possibly got a cease-and-desist from Netflix or similar.

**Comment by GogoAkira** [comment]
Confirming a/v bitrates watching Queen Sono
Chrome 96/1403
Edge 128/5110
Affects color a little, grainyness and even frame rate difference is very noticeable.

**Comment by morsik** [comment]
I also noticed this problem on Chrome on Linux :(
FullHD is not working, 5.1 audio works tough.

**Comment by supdotcom** [comment]
Same problem.

**Comment by dimapoint** [comment]
hi, how do you all see the bitrate of your stream? noob here

**Comment by psvita123** [comment]
@dimapoint 
CTRL + ALT + SHIFT + D. This is for checking the bitrate.
CTRL + ALT + SHIFT + S(only works if u use this extension). This is for selecting the bitrate.

**Comment by dimapoint** [comment]
thank you so much!

**Comment by truedread** [comment]
Closing as major changes have been made that have probably fixed this.
