### ISSUE TITLE
Force Netflix to stream from Local CDN/Manually Specify CDN

### ISSUE THREAD

**Issue by maskcolab** [truedread/netflix-1080p#86]
Hi,

Netflix has a CDN in my country in partnership with an upstream provider, which my ISP uses. Sometimes, for unknown reasons, Netflix streams from foreign CDN instead of the local one. And while that happens, I can't also see local CDN in the list of available CDNs (using ctrl+alt combo) so to manually select it for streaming. This negatively affects the playback quality as international speed to foreign CDNs are pretty abysmal amid the COVID19 pandemic. 

I do know the IP of the local CDN. And it's available when I ping it. So, this got me wondering whether I could specify it somewhere, so as to force Netflix to stream from it.

**Comment by truedread** [comment]
This is not supported by the scope of this extension unfortunately.
