### ISSUE TITLE
1080P doesnt work anymore

### ISSUE THREAD

**Issue by NoFVCKSGiven** [truedread/netflix-1080p#9]
Looks like the (Chrome) extension doesnt work anymore tried everything uninstalling, clearing cache doesnt work

**Comment by rajamalw** [comment]
Yes. Not working anymore.

**Comment by deewfrank** [comment]
yes.. not working (Chrome/Firefox)

**Comment by bezirg** [comment]
Not working on Linux/Chrome66

**Comment by Arg0s1080** [comment]
idem... since yesterday not working (Chrome 66-67 on Linux & Windows)

**Comment by ryanmusante** [comment]
+1

**Comment by truedread** [comment]
Fixed in latest commit.
