### ISSUE TITLE
Should this work in Firefox, too?

### ISSUE THREAD

**Issue by Brandhand** [truedread/netflix-1080p#91]
Is this extension supposed to work in Firefox? I built the source-code from 1.19 into an addon, signed it through mozilla and could install it. Unfortunately it doesn't show any Netflix video. I either get an errror-page or sometimes the screen gets black and nothing happens.

In Chrome it works for me with version 1.19. But my problem there is, I have tearing when watching.

**Comment by bit2shift** [comment]
Did you include the fix from #89?
That and enabling 5.1 audio seems to fix the issue that arose this week (#90).

**Comment by Brandhand** [comment]
Yeah, I did add the patch, even tried the 1.18. But always the same result. even with different settings on Audio5.1.

Strangely enough the 1.18 is still working in Chrome without the patch. But as I mentioned tearing makes it almost useless to watch.

**Comment by ItsNickBarry** [comment]
https://github.com/vladikoff/netflix-1080p-firefox

**Comment by truedread** [comment]
Firefox is not supported on this repo. Please try a fork.
