### ISSUE TITLE
Still works on Microsoft Edge

### ISSUE THREAD

**Issue by familiarrStrangerr** [truedread/netflix-1080p#97]
So this add on is still working on Microsoft Edge (new Chromium build) Version 81.0.416.72 (Official build) (64-bit)

If you are having issue try Edge

**Comment by EmyShoka** [comment]
Yeah, because the drm of edge is not capped at 720p, so you don't need the addon on Edge

**Comment by emretanriverdi** [comment]
@EmyShoka in Windows it's not.

In MacOS it's capped to 720p, the extension fixes it.

**Comment by EmyShoka** [comment]
Oh, i didn't knew that, good to know

**Comment by psvita123** [comment]
@familiarrStrangerr hi, i am trying to use this one edge, doesn`t work for me as soon as i play some video it shows an error, am i missing something here? Can you help me? Just to confirm you able to use the bitrate menu in edge, right?

**Comment by familiarrStrangerr** [comment]
> @familiarrStrangerr hi, i am trying to use this one edge, doesn`t work for me as soon as i play some video it shows an error, am i missing something here? Can you help me? Just to confirm you able to use the bitrate menu in edge, right?

Functional as usual. About your problem are you on the same Edge version? Check that too and I would also add that I have tested on MacOS because on Windows I have the Windows 10 Netflix app so I have checked only on the MacOS Mojave.

**Comment by starm7md** [comment]
@familiarrStrangerr  i have the same error  D7354 on Microsoft edge (Chromium build) Version 81.0.416.72 as soon as i play some video it shows error  D7354  ,iam on windows 10 , please begging for help 

![n shoot](https://user-images.githubusercontent.com/65809932/82728839-af4ced00-9cfb-11ea-81a5-f205ec758fe9.png)

![n shoot 2](https://user-images.githubusercontent.com/65809932/82728844-b70c9180-9cfb-11ea-8409-1c0b25d6b929.png)

**Comment by familiarrStrangerr** [comment]
> @familiarrStrangerr i have the same error D7354 on Microsoft edge (Chromium build) Version 81.0.416.72 as soon as i play some video it shows error D7354 ,iam on windows 10 , please begging for help
> 
> ![n shoot](https://user-images.githubusercontent.com/65809932/82728839-af4ced00-9cfb-11ea-81a5-f205ec758fe9.png)
> 
> ![n shoot 2](https://user-images.githubusercontent.com/65809932/82728844-b70c9180-9cfb-11ea-8409-1c0b25d6b929.png)

If you are on Windows 10 why are you bothering with these, install the official Netflix app from the Windows Store. That application plays everything on the highest bitrate if you have decent internet speed. I only use this addon for Mac.

**Comment by starm7md** [comment]
I dont have a good internet speed you got the reason every minute the quality changes so i need this extension to force the browser , if you know anyway that i can fix this its very appreciate

**Comment by familiarrStrangerr** [comment]
> I dont have a good internet speed you got the reason every minute the quality changes so i need this extension to force the browser , if you know anyway that i can fix this its very appreciate

I really don't know, you can try reinstalling the browser or clearing the browser data but other than that I have no idea. Maybe OS is a factor, maybe there are some code difference in the mac which is allowing the addon to work as usual.

**Comment by starm7md** [comment]
thank you anyway , can you just tell me what version of 1080p extension do you use on microsoft edge browser

**Comment by familiarrStrangerr** [comment]
> thank you anyway , can you just tell me what version of 1080p extension do you use on microsoft edge browser

Version 1.19

![Screenshot 2020-05-24 at 11 57 51 AM](https://user-images.githubusercontent.com/65554602/82747391-dbc53f80-9db5-11ea-9fdc-510c015113ec.png)

**Comment by emretanriverdi** [comment]
@familiarrStrangerr maybe you can close the issue?

**Comment by lkmvip** [comment]
emm,,,,,,,,,If your are interested,  watch this, I have explained how you can operate
(WIN10 ChromiumEDGE)
https://github.com/truedread/netflix-1080p/pull/95#issuecomment-633217119


I may upload code to github in the near future

**Comment by psvita123** [comment]
> emm,,,,,,,,,If your are interested, watch this, I have explained how you can operate
> (WIN10 ChromiumEDGE)
> [#95 (comment)](https://github.com/truedread/netflix-1080p/pull/95#issuecomment-633217119)
> 
> I may upload code to github in the near future

looking forward to your update, for similar reasons as @starm7md I need the extension to work on edge. Been looking forward to this for a long time. Fingers crossed!

**Comment by starm7md** [comment]
> emm,,,,,,,,,If your are interested, watch this, I have explained how you can operate
> (WIN10 ChromiumEDGE)
> [#95 (comment)](https://github.com/truedread/netflix-1080p/pull/95#issuecomment-633217119)
> 
> I may upload code to github in the near future

unfortunately i don't know any this about coding , so all what you have said i didn't get it and can't figure it by myself , and of course i will appreciate u help if you can update the code in the future that would be great !

**Comment by starm7md** [comment]
> > emm,,,,,,,,,If your are interested, watch this, I have explained how you can operate
> > (WIN10 ChromiumEDGE)
> > [#95 (comment)](https://github.com/truedread/netflix-1080p/pull/95#issuecomment-633217119)
> > I may upload code to github in the near future
> 
> looking forward to your update, for similar reasons as @starm7md I need the extension to work on edge. Been looking forward to this for a long time. Fingers crossed!

the only way to make the extension works by turning off the hardware acceleration , and its bad because some devices need this option because of low specs but its the only way u can use it on edge , i hope in the future they will fix this issue

**Comment by jangxx** [comment]
@starm7md 

>I dont have a good internet speed you got the reason every minute the quality changes so i need this extension to force the browser , if you know anyway that i can fix this its very appreciate

But if you force a higher bitrate, the playback stops for buffering instead of dynamically adapting to your internet. Wouldn't it be a better option to just use the download functionality of the official Win 10 app and not even bother with streaming if your connection is that unstable?

**Comment by starm7md** [comment]
> @starm7md
> 
> > I dont have a good internet speed you got the reason every minute the quality changes so i need this extension to force the browser , if you know anyway that i can fix this its very appreciate
> 
> But if you force a higher bitrate, the playback stops for buffering instead of dynamically adapting to your internet. Wouldn't it be a better option to just use the download functionality of the official Win 10 app and not even bother with streaming if your connection is that unstable?

if i want to use win 10 app while my internet  is unstable , the birate will keep change every 5 minutes so i will need the extension anyway , and beside this i want to use other great extensions on netflix that i can only use them on browser

**Comment by lkmvip** [comment]
try this
https://github.com/lkmvip/netflix-4K-DDplus/releases/tag/1.0

**Comment by starm7md** [comment]
@lkmvip  now it works . thanks a lot to you

**Comment by truedread** [comment]
Closing as major changes have been made that have probably fixed this.
