### ISSUE TITLE
Are you OK ? 

### ISSUE THREAD

**Issue by om26er** [truedread/netflix-1080p#98]
I just wanted to know if you @truedread are OK. My concern is if the Netflix guys got to you with their lawyers etc ? Hope you are fine.

**Comment by MFrost2019** [comment]
@truedread You live there? We're all waiting for you. Greetings :)

**Comment by davwheat** [comment]
![image](https://user-images.githubusercontent.com/7406822/83571235-5103e380-a51f-11ea-8ec2-44e5d36b1b2f.png)

bearing in mind his GitHub has had activity for the past few weeks, I think that he's fine...

**Comment by om26er** [comment]
> bearing in mind his GitHub has had activity for the past few weeks, I think that he's fine...

Sounds good ;-)
