### ISSUE TITLE
I can't play most of the videos

### ISSUE THREAD

**Issue by Sametebesek** [truedread/netflix-1080p#99]
Hi, uh today when i tried to watch prison break i couldn't BUT i was able to watch season 5 of black mirror. So wtf is going on is that just happens to me? Anyone who's also can't play most of the videos(or all of them) please write it down so maybe we can find a solution...

**Comment by Sametebesek** [comment]
Btw i can play season 5 of black mirror properly with the extension but i can't play prison break, or season 1 of black mirror, etc.

**Comment by Sametebesek** [comment]
any solution?

**Comment by Mering** [comment]
I can't play  anymore too. Now i use  netflix uwp.

**Comment by Mering** [comment]
https://github.com/jangxx/netflix-1080p/releases/tag/v1.20
this can work！！！

**Comment by Sametebesek** [comment]
It works, thanks a lot!

**Comment by GgZak** [comment]
Yoo thanks a lot it actually works !! now i can watch anime tid*es in 1080p lol

**Comment by truedread** [comment]
Closing as major changes have been made that have probably fixed this.
